### ISSUE TITLE
提议暂时关掉Pylint的action

### ISSUE THREAD

**Issue by LaoshuBaby** [WhitePaper233/BangumiAPI#4]
要做到完美是不太可能的，即使用pylint跑pylint自己也跑不到10分，而目前的情况下即使是7分以上，也依然会返回一个错误值
长期在狼来了的情况下，可能会造成真的需要lint的东西被习惯性忽视，建议暂停这几个测试？

（当然，如果项目有开发习惯的话，权当这一条是冒犯（另外没有写单测真的抱歉，咕））

---
BTW, dev啥时候合进main啊？

**Comment by WhitePaper233** [comment]
lint确实不着急 我也暂时不怎么想管lint 已经禁用了 等最后开发的差不多了再开

**Comment by WhitePaper233** [comment]
dev合并的话得等等 还有很多api没实现 大概是考完试之后的事情了（（（

**Comment by LaoshuBaby** [comment]
> dev合并的话得等等 还有很多api没实现 大概是考完试之后的事情了（（（

礼貌询问：应该是高考完了吗 ~~（但我还没毕业论文答辩，危）~~

**Comment by WhitePaper233** [comment]
> 

确实考完了 最近在摸鱼（（（
